const data = {
  products: [
    {
      name: "Aviator Leather",
      slug: "aviator-leather",
      category: "Jackets",
      subCategory: "Leather",
      image: "/images/leather_jacket.png",
      price: 250,
      brand: "Schott",
      rating: 4.9,
      numReviews: 15,
      countInStock: 5,
      description: "Classic leather aviator jacket",
      deliveryTime: "5-7 days",
      dimensions: "50x40x10 cm",
      weight: "1.5 kg",
      cbm: 0.02,
      hsCode: "4203.10.00",
    },
    {
      name: "Heritage Boots",
      slug: "heritage-boots",
      category: "Shoes",
      subCategory: "Boots",
      image: "/images/leather_boots.png",
      price: 180,
      brand: "Red Wing",
      rating: 4.8,
      numReviews: 12,
      countInStock: 8,
      description: "Durable leather heritage boots",
      deliveryTime: "5-7 days",
      dimensions: "35x25x15 cm",
      weight: "2.0 kg",
      cbm: 0.013,
      hsCode: "6403.91.00",
    },
    {
      name: "City Tote",
      slug: "city-tote",
      category: "Accessories",
      subCategory: "Sac",
      image: "/images/leather_bag.png",
      price: 120,
      brand: "Aurum",
      rating: 4.7,
      numReviews: 20,
      countInStock: 15,
      description: "Elegant tan leather handbag",
      deliveryTime: "4-6 days",
      dimensions: "40x35x12 cm",
      weight: "0.8 kg",
      cbm: 0.017,
      hsCode: "4202.21.00",
    },
    {
      name: "Arc Designer Lamp",
      slug: "arc-designer-lamp",
      category: "Home",
      subCategory: "Lighting",
      image: "/images/lamp.png",
      price: 320,
      brand: "Lumina",
      rating: 4.8,
      numReviews: 25,
      countInStock: 10,
      description: "Elegant arc floor lamp with warm ambient light",
      deliveryTime: "7-10 days",
      dimensions: "120x30x30 cm",
      weight: "5.5 kg",
      cbm: 0.108,
      hsCode: "9405.20.00",
    },
    {
      name: "Pulse RGB Strip",
      slug: "pulse-rgb-strip",
      category: "Home",
      subCategory: "LEDs",
      image: "/images/led_strip.png",
      price: 45,
      brand: "GlowTech",
      rating: 4.6,
      numReviews: 40,
      countInStock: 50,
      description: "Smart RGB LED strip with music sync features",
      deliveryTime: "2-4 days",
      dimensions: "15x15x5 cm",
      weight: "0.3 kg",
      cbm: 0.001,
      hsCode: "9405.40.00",
    },
    {
      name: "Infinity OLED 4K",
      slug: "infinity-oled-4k",
      category: "Electronics",
      subCategory: "TV",
      image: "/images/tv.png",
      price: 2400,
      brand: "Vision",
      rating: 5.0,
      numReviews: 18,
      countInStock: 4,
      description: "Ultra-thin 75-inch 4K OLED TV with deep blacks",
      deliveryTime: "10-14 days",
      dimensions: "170x100x20 cm",
      weight: "35.0 kg",
      cbm: 0.34,
      hsCode: "8528.72.00",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      subCategory: "Casual",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      deliveryTime: "3-5 days",
      dimensions: "30x20x2 cm",
      weight: "0.2 kg",
      cbm: 0.001,
      hsCode: "6105.10.00",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      subCategory: "Formal",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      deliveryTime: "3-5 days",
      dimensions: "30x20x2 cm",
      weight: "0.2 kg",
      cbm: 0.001,
      hsCode: "6105.10.00",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      subCategory: "Casual",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      deliveryTime: "3-5 days",
      dimensions: "30x20x2 cm",
      weight: "0.2 kg",
      cbm: 0.001,
      hsCode: "6105.10.00",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      subCategory: "Sports",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants",
      deliveryTime: "3-5 days",
      dimensions: "40x30x3 cm",
      weight: "0.4 kg",
      cbm: 0.004,
      hsCode: "6203.42.00",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      subCategory: "Casual",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
      deliveryTime: "3-5 days",
      dimensions: "40x30x3 cm",
      weight: "0.4 kg",
      cbm: 0.004,
      hsCode: "6203.42.00",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      subCategory: "Formal",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
      deliveryTime: "3-5 days",
      dimensions: "40x30x3 cm",
      weight: "0.4 kg",
      cbm: 0.004,
      hsCode: "6203.42.00",
    },
  ],
  categories: [
    { name: "Jackets", slug: "jackets", description: "Luxury outwear" },
    {
      name: "Accessories",
      slug: "accessories",
      description: "Premium accessories",
    },
    { name: "Furniture", slug: "furniture", description: "High-end decor" },
  ],
  brands: [
    { name: "Schott", slug: "schott", description: "Legendary American brand" },
    { name: "Omega", slug: "omega", description: "Swiss luxury watches" },
    {
      name: "Herman Miller",
      slug: "herman-miller",
      description: "Iconic furniture",
    },
  ],
  users: [
    {
      name: "Admin User",
      email: "admin@example.com",
      password: "password123",
      isAdmin: true,
    },
    {
      name: "John Doe",
      email: "john@example.com",
      password: "password123",
      isAdmin: false,
    },
  ],
};
export default data;
